[package]
name = "learning_rust_os"
version = "0.1.0"
authors = ["Brandon Dyer <brandondyer64@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.8.0"
